#
# Module manifest for module 'PS-StoreOnce'
#
# Generated by: Markus Kraus
#
# Generated on: 31-05-2016
#

@{
  RootModule        = 'PS-StoreOnce'
  ModuleVersion     = '0.5.1'
  GUID              = '03cf476a-c474-4f92-8afc-afe521162441'
  Author            = 'Markus Kraus'
  CompanyName       = 'mycloudrevolution'
  Copyright         = '(c) 2016 Markus Kraus. All rights reserved.'
  PowerShellVersion = '3.0'
  FunctionsToExport = '*'
  CmdletsToExport   = '*'
  VariablesToExport = '*'
  AliasesToExport   = '*'
}